export const artists = [
  { username: "Amir Patel", category: ["writing"] },
  { username: "_baomii", category: ["illustration"] },
  { username: "3rzhuobabypink", category: ["fashion"] },
  { username: "artofsukmina", category: ["illustration"] },
  { username: "beanynne", category: ["illustration"] },
  { username: "benkipo", category: ["illustration"] },
  { username: "bespokeshape", category: ["illustration"] },
  { username: "birdfrogdraws", category: ["illustration"] },
  { username: "buctoria_owo", category: ["photography", "fashion"] },
  { username: "buttmvnch", category: ["illustration"] },
  {
    username: "clouwdez",
    category: ["illustration", "photography", "fashion"],
  },
  { username: "co_ctrl", category: ["illustration", "fashion"] },
  { username: "copyghost_", category: ["fashion"] },
  { username: "floracryy", category: ["handcraft"] },
  { username: "gem.vving", category: ["fashion"] },
  { username: "ginger.ange1", category: ["fashion"] },
  { username: "gubean", category: ["illustration", "writing"] },
  { username: "hanatyszka", category: ["illustration"] },
  { username: "hapimonsta", category: ["illustration"] },
  { username: "heykeeks", category: ["illustration"] },
  { username: "heymugi", category: ["illustration", "handcraft"] },
  { username: "hurricanetai", category: ["illustration"] },
  { username: "ickygirlart", category: ["illustration"] },
  { username: "jessenpaints", category: ["illustration"] },
  { username: "julie.egg", category: ["illustration"] },
  { username: "jyahm_", category: ["illustration"] },
  { username: "jyuub", category: ["illustration"] },
  { username: "kailahashimoto", category: ["fashion"] },
  { username: "laikalaika00", category: ["illustration"] },
  { username: "linkandpage", category: ["handcraft"] },
  { username: "lisa.sumiko", category: ["handcraft"] },
  { username: "m0ldbat", category: ["illustration", "photography"] },
  { username: "meiiomi", category: ["illustration"] },
  { username: "milkytrinh", category: ["illustration"] },
  { username: "miyu.ce", category: ["photography", "fashion"] },
  { username: "mooooonbug", category: ["illustration"] },
  { username: "mothcub_", category: ["illustration"] },
  { username: "nailuj.naze", category: ["illustration"] },
  { username: "nikoco_11", category: ["illustration"] },
  { username: "o3oeve", category: ["illustration"] },
  { username: "oddrabbits", category: ["illustration"] },
  { username: "om3lette", category: ["illustration"] },
  { username: "onenhillion", category: ["illustration"] },
  { username: "paiphos", category: ["illustration"] },
  { username: "paluumin", category: ["illustration"] },
  { username: "pameluft", category: ["illustration", "fashion"] },
  { username: "peechmart", category: ["illustration"] },
  { username: "pyitu", category: ["illustration"] },
  { username: "refinedacne", category: ["illustration"] },
  { username: "rxcked", category: ["writing"] },
  { username: "scraps666", category: ["fashion"] },
  { username: "shopdokidoki", category: ["handcraft"] },
  { username: "sighsra", category: ["illustration"] },
  { username: "sonagee_", category: ["illustration"] },
  { username: "sonnyfebruary", category: ["illustration"] },
  { username: "soupandcats", category: ["illustration"] },
  { username: "sukinapan", category: ["illustration"] },
  { username: "sumimatsuno", category: ["fashion"] },
  { username: "taccaeri", category: ["illustration"] },
  { username: "taliotalio.o", category: ["fashion"] },
  { username: "teyoliveoil", category: ["illustration"] },
  { username: "the.intertidal", category: ["photography", "writing"] },
  { username: "treasuringz", category: ["fashion"] },
  { username: "unfortunateplottwist", category: ["handcraft"] },
  { username: "versucccy", category: ["illustration"] },
  { username: "waterspecimens", category: ["photography"] },
  { username: "yancantdraw", category: ["illustration"] },
  { username: "yasmini.gif", category: ["illustration"] },
  { username: "yeuujjn", category: ["illustration"] },
  { username: "ziewotka", category: ["illustration"] },
];

export const filters = [
  "illustration",
  "photography",
  "fashion",
  "handcraft",
  "writing",
];
